export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const COUNT_PROJECT_TASKS = "COUNT_PROJECT_TASKS"
export const SUM_PROJECT_TASKS= "SUM_PROJECT_TASKS"
export const SUM_PROJECTS= "SUM_PROJECTS"