
###
////// READ
/// GET All Projects
GET http://localhost:8080/api/project/all


###
////// GET Single Project
GET http://localhost:8080/api/project/PPM2


###
////// UPDATE
// PUT PROJECT
PUT http://localhost:8080/api/project
Content-Type: application/json

{
  "id":"2",
  "projectName":"Use AWS to host Project",
  "projectUUID":"PPM2",
  "description":"Use AWS to host application servers. React + Spring + mySQL"
}

