


###
////// Null Task Object
/// addProjectTaskToBacklog

POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{

}

###
////// Mishapen Task Object
/// addProjectTaskToBacklog

POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{
  "summary": "",
  "priority": "1"
}

###
////// Project Does not exist
/// addProjectTaskToBacklog
POST http://localhost:8080/api/backlog/FAKE
Content-Type: application/json

{
  "summary": "Buy Dog Food",
  "priority": "1"

}

###
////// Project Does not exist
/// getProjectBacklog
GET http://localhost:8080/api/backlog/FAKE

###
////// TASK on real project does not exist
/// getProjectTask
GET http://localhost:8080/api/backlog/PPM2/PPM6-3

###
////// Project does not exist
/// getProjectTask
GET http://localhost:8080/api/backlog/FAKE/PPM2-3


###
///// UPDATE TASK BY SEQUENCE Bad Data
/// updateProjectTask
PATCH http://localhost:8080/api/backlog/PPM2/PPM2-3
Content-Type: application/json

{
  "id": 3,
  "projectSequence": "PPM2-3",
  "summary": "",
  "acceptanceCriteria": null,
  "status": "TODO",
  "priority": 1,
  "dueDate": null,
  "projectUUID": "PPM2",
  "created_At": "2022-01-28T00:24:12.000+00:00",
  "updated_At": null
}

###
///// UPDATE TASK BY SEQUENCE PROJECT NOT EXISTS
/// updateProjectTask
PATCH http://localhost:8080/api/backlog/FAKE/PPM2-33
Content-Type: application/json

{
  "id": 3,
  "projectSequence": "PPM2-3",
  "summary": "PROJECT NOT EXIST",
  "acceptanceCriteria": null,
  "status": "TODO",
  "priority": 1,
  "dueDate": null,
  "projectUUID": "PPM2",
  "created_At": "2022-01-28T00:24:12.000+00:00",
  "updated_At": null
}
