###
////// CREATE
/// POST single Project
POST http://localhost:8080/api/project
Content-Type: application/json

{
  "projectName": "Make PPM Tool",
  "projectUUID": "PPM1",
  "description": "I need to make a project management tool for company"
}

<> 2022-01-27T161933.201.json
<> 2022-01-27T161654.201.json
<> 2022-01-27T161533.201.json
<> 2022-01-27T161204.201.json
<> 2022-01-27T160703.201.json
<> 2022-01-27T145847.201.json



###
POST http://localhost:8080/api/project
Content-Type: application/json


{
  "projectName": "Host Project on Cloud",
  "projectUUID": "PPM2",
  "description": "Find a way to host on cloud."
}

<> 2022-01-27T161933-1.201.json
<> 2022-01-27T161654-1.201.json
<> 2022-01-27T161533-1.201.json
<> 2022-01-27T161204-1.201.json
<> 2022-01-27T160703-1.201.json
<> 2022-01-27T145847-1.201.json



###
POST http://localhost:8080/api/project
Content-Type: application/json


{
  "projectName": "Present Project",
  "projectUUID": "TALK",
  "description": "Present & demo PPM"
}



###
/// POST Tasks

POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{
  "summary": "Clear whiteboard",
  "priority": "3"

}


###
POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{
  "summary": "Refractor Code",
  "priority": "2"

}




###
POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{
  "summary": "Release Project",
  "priority": "1"

}





