###
////// CREATE
/// POST single Project
POST http://localhost:8080/api/project
Content-Type: application/json

{
  "projectName": "Make zPPM Tool",
  "projectUUID": "PPM12",
  "description": "I need to make a project management tool for company"
}




###
POST http://localhost:8080/api/project
Content-Type: application/json


{
  "projectName": "Host Project on Cloud",
  "projectUUID": "PPM2",
  "description": "Find a way to host on cloud."
}


###
POST http://localhost:8080/api/project
Content-Type: application/json


{
  "projectName": "Present Project",
  "projectUUID": "TALK",
  "description": "Present & demo PPM"
}



###
/// POST Tasks

POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{
  "summary": "Clear whiteboard",
  "priority": "3"

}


###
POST http://localhost:8080/api/backlog/HELLO
Content-Type: application/json

{
  "summary": "Refractor Code",
  "priority": "2"

}


###
POST http://localhost:8080/api/backlog/PPM2
Content-Type: application/json

{
  "summary": "Release Project",
  "priority": "1"

}

###
POST http://localhost:8080/api/backlog/PPM1
Content-Type: application/json

{
"summary": "Release Project",
"priority": "1"

}





